server:
  port: 7091
  servlet:
    context-path: /


spring:
  # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
  datasource:
    dynamic:
      patterns: com.yuntian.mybatisdemo.dao.*
    username: test
    password: test944610721
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 6000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filters: stat
      connection-init-sqls: set names utf8mb4;
      master:
        url: jdbc:mysql://121.199.71.179:33065/replicas_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull
      slave:
        url: jdbc:mysql://121.199.71.179:33066/replicas_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: "PARTIAL"
    default-executor-type: "SIMPLE"
    map-underscore-to-camel-case: true
    local-cache-scope: "SESSION"
    jdbc-type-for-null: "NULL"

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


logging:
  level:
    com.yuntian: debug
